# 
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-8812au-test

on:
  workflow_dispatch:

jobs:

  build_openwrt:

    name: OpenWrt-8812au-test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Checkout rlt8812bu makefile
        uses: actions/checkout@v2
        with:
          repository: xu373297464/RTL88x2BU-OpenWRT
          ref: linux5.11+
          path: package/kernel/RTL88x2BU-OpenWRT

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
#          docker rmi `docker images -q`
#          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
#          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
#          sudo -E apt-get update
#          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
#          sudo -E apt-get -y autoremove --purge
#          sudo -E apt-get clean
          df -h

      - name: Generate configuration file
        run: |
          cat package/kernel/RTL88x2BU-OpenWRT/Makefile
          make defconfig
          echo "test : start"
          grep -n 88 .config
          echo "test : end"

      - name: Compile firmware
        run: |
          echo "test : start"
          grep -n 88 .config
          echo "test : end"

