# 
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-8812au-test

on:
  workflow_dispatch:

jobs:

  build_openwrt:

    name: OpenWrt-8812au-test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Checkout rlt8812bu makefile
        uses: actions/checkout@v2
        with:
          repository: xu373297464/RTL88x2BU-OpenWRT
          ref: linux5.11+
          path: package/kernel/RTL88x2BU-OpenWRT

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          df -h

      - name: Generate configuration file
        run: |
          cat package/kernel/RTL88x2BU-OpenWRT/Makefile
          make defconfig
          echo "test : start"
          grep -n 88 .config
          echo "test : end"

      - name: Compile firmware
        run: |
          echo "test : start"
          grep -n 88 .config
          echo "test : end"

